### ISSUE TITLE
Exception: Error compiling program when running system

### ISSUE THREAD

**Issue by luancarvalhomartins** [MobleyLab/blues#165]
Dear all,

I am trying to run an MCMD simulation using BLUES. When installing using Conda, I had problems setting the Cuda platform, so I am using a manually compiled version. All TestCuda* run fine. I prepared a system using tleap and minimization (with `simulations.md.minimizeEnergy(maxIterations=0)`) and a short equilibration (`simulations.md.step(10000)`). But then:

```
blues = BLUESSimulation(simulations, cfg['simulation'])
blues.run()
```
yields

```
Traceback (most recent call last):
  File "../../../../../../scripts/commands.py", line 180, in <module>
    blues.run()
  File "/mnt/nfs/exa/work/lmartins/miniconda3/envs/blues/blues-master/blues/simulation.py", line 1246, in run
    self._stepNCMC(nstepsNC, moveStep)
  File "/mnt/nfs/exa/work/lmartins/miniconda3/envs/blues/blues-master/blues/simulation.py", line 1056, in _stepNCMC
    ncmc_state0 = self.getStateFromContext(self._ncmc_sim.context, self._state_keys)
  File "/mnt/nfs/exa/work/lmartins/miniconda3/envs/blues/blues-master/blues/simulation.py", line 905, in getStateFromContext
    state = context.getState(**state_keys)
  File "/nfs/exa/work/lmartins/miniconda3/envs/blues/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 5064, in getState
    state = _openmm.Context_getState(self, types, enforcePeriodicBox, groups_mask)
Exception: Error compiling program: (710): error: expected a ")"

(711): error: expected a ")"

(759): error: expected an expression

(769): error: too many arguments in invocation of macro "make_TempType3"

(769): error: expected an expression

(770): error: expected an expression

(772): warning: variable "gaussianIndex" was declared but never referenced

(773): warning: variable "uniformIndex" was declared but never referenced

(761): warning: variable "forceScale" was declared but never referenced

6 errors detected in this compilation.
```
 
What do those errors mean? I am using a system with PBC and truncated octahedral box (generated using `solvateOct` in tleap). My ligand is indeed called LIG.

Thank you!

**Comment by davidlmobley** [comment]
Sorry for the delay, missed the GitHub notification. This looks a problem with OpenMM and not with BLUES, I think, as you're getting "compilation" errors from OpenMM. But tagging @sgill2 and @bergazin ...

**Comment by sgill2** [comment]
Hi @luancarvalhomartins,
Could you post the scripts/files you used (or a minimal example)? From the traceback you posted it looks like there's a problem with openmm, but I can take a look and see if anything else seems out of place.  Also, have you tried running normal MD simulations on the CUDA platform with openmm?
